categories:

  XimaTypo3Calendar:
    label: 'XIMA TYPO3 Calendar'

settings:

  xima_typo3_calendar.eventShowPid:
    label: 'Event detail page'
    description: 'The page where the single view of a calendar event and appointment is displayed.'
    category: XimaTypo3Calendar
    type: page
    default: 0
