name: xima/calendar
table: tx_ximatypo3calendar_domain_model_calendar
prefixFields: false
labelField: title
languageAware: false
workspaceAware: false
editLocking: false
security:
  ignorePageTypeRestriction: true
fields:
  - identifier: title
    type: Text
    label: Title
  - identifier: description
    type: Textarea
    label: Description
    enableRichtext: true
  - identifier: entries_tab
    type: Tab
    label: Entries
  - identifier: entries
    type: Collection
    label: Entries
    foreign_table: tx_ximatypo3calendar_domain_model_entry
    foreign_field: calendar
    allowed: tx_ximatypo3calendar_domain_model_entry
