name: xima/event-appointment
table: tx_ximatypo3calendar_domain_model_entry
prefixFields: false
labelField: start_date
languageAware: false
workspaceAware: false
editLocking: false
restriction:
  startTime: false
  endTime: false
  userGroup: false
typeField: record_type
typeName: event-appointment
fields:
  - identifier: calendar
    type: Select
    useExistingField: true
  - identifier: event
    type: Select
    renderType: selectSingle
    foreign_table: tx_ximatypo3calendar_domain_model_event
    required: true
  - identifier: datetime_palette
    type: Palette
    fields:
      - identifier: start_date
        type: DateTime
        required: true
        dbType: datetime
        format: datetime
        disableAgeDisplay: true
      - identifier: end_date
        type: DateTime
        dbType: datetime
        format: datetime
        disableAgeDisplay: true
      - identifier: all_day
        type: Checkbox
        default: 0
  - identifier: canceled
    type: Checkbox
    default: 0
  - identifier: modified_date
    type: DateTime
    dbType: datetime
  - identifier: content_tab
    type: Tab
  - identifier: description
    type: Textarea
    enableRichtext: true
  - identifier: location_tab
    type: Tab
  - identifier: type
    type: Select
    renderType: selectSingle
    items:
      - value: inPerson
        label: 'Präsenz'
      - value: online
        label: 'Online'
      - value: hybrid
        label: 'Hybrid'
  - identifier: online_link
    type: Link
    allowedTypes:
      - url
  - identifier: location
    type: Relation
    foreign_table: tx_ximatypo3calendar_domain_model_location
    required: true
    allowed: tx_ximatypo3calendar_domain_model_location
    size: 1
  - identifier: directions
    type: Textarea
    rows: 5
  - identifier: speakers_tab
    type: Tab
  - identifier: speakers
    type: Relation
    foreign_table: tx_ximatypo3calendar_domain_model_speaker
    allowed: tx_ximatypo3calendar_domain_model_speaker
