name: xima/event-appointment
table: tx_ximatypo3calendar_domain_model_entry
prefixFields: false
labelField: title
languageAware: false
workspaceAware: false
editLocking: false
typeField: record_type
typeName: event-appointment
fields:
  - identifier: calendar
    type: Select
    useExistingField: true
  - identifier: event
    type: Select
    renderType: selectSingle
    foreign_table: tx_ximatypo3calendar_domain_model_event
    required: true
  - identifier: title
    type: Text
  - identifier: datetime_palette
    type: Palette
    fields:
      - identifier: start_date
        type: DateTime
        required: true
        dbType: datetime
        format: datetime
        disableAgeDisplay: true
      - identifier: end_date
        type: DateTime
        dbType: datetime
        format: datetime
        disableAgeDisplay: true
      - identifier: all_day
        type: Checkbox
        default: 0
  - identifier: canceled
    type: Checkbox
    default: 0
  - identifier: content_tab
    type: Tab
  - identifier: description
    type: Textarea
    enableRichtext: true
  - identifier: url
    type: Link
    allowedTypes:
      - url
  - identifier: files
    type: File
    allowed: common-media-types
  - identifier: location_tab
    type: Tab
  - identifier: type
    type: Select
    renderType: selectSingle
    items:
      - value: presence
        label: 'Präsenz'
      - value: online
        label: 'Online'
      - value: hybrid
        label: 'Hybrid'
  - identifier: location
    type: Relation
    foreign_table: tx_ximatypo3calendar_domain_model_location
    required: true
    allowed: tx_ximatypo3calendar_domain_model_location
    size: 1
  - identifier: address
    type: Textarea
    rows: 3
  - identifier: online_link
    type: Link
    allowedTypes:
      - url
  - identifier: directions
    type: Textarea
    rows: 5
  - identifier: registration_tab
    type: Tab
  - identifier: registration_palette
    type: Palette
    fields:
      - identifier: requires_registration
        type: Checkbox
        default: 0
      - identifier: registration_link
        type: Link
        allowedTypes:
          - url
          - page
      - identifier: registration_deadline
        type: DateTime
        dbType: datetime
      - identifier: fee
        type: Text
  - identifier: people_tab
    type: Tab
  - identifier: speakers
    type: Relation
    foreign_table: tx_ximatypo3calendar_domain_model_speaker
    allowed: tx_ximatypo3calendar_domain_model_speaker
  - identifier: hosts
    type: Relation
    foreign_table: fe_users
    allowed: fe_users
