name: xima/event
table: tx_ximatypo3calendar_domain_model_event
prefixFields: false
labelField: title
languageAware: false
workspaceAware: false
editLocking: true
restriction:
  startTime: false
  endTime: false
  userGroup: false
security:
  ignorePageTypeRestriction: true
fields:
  - identifier: event_info_palette
    type: Palette
    fields:
      - identifier: title
        type: Text
        maxLength: 255
        size: 60
      - identifier: language
        type: Select
        renderType: selectSingle
        required: true
        items:
          - value: ''
            label: 'Alle Sprachen'
          - value: de
            label: 'Deutsch'
          - value: en
            label: 'Englisch'
  - identifier: description
    type: Textarea
    enableRichtext: true
  - identifier: additional_information
    type: Textarea
    rows: 3
  - identifier: url
    type: Link
    allowedTypes:
      - url
  - identifier: preview_image
    type: File
    allowed: common-image-types
    maxitems: 1
  - identifier: files
    type: File
  - identifier: publishing_tab
    type: Tab
  - identifier: publishing_palette
    type: Palette
    fields:
      - identifier: publish_to_website
        type: Checkbox
        default: 0
      - identifier: publish_to_feed
        type: Checkbox
        default: 0
      - identifier: publish_date
        type: DateTime
  - identifier: appointments
    type: Collection
    foreign_table: tx_ximatypo3calendar_domain_model_entry
    foreign_field: event
    allowed:
      - event-appointment
  - identifier: appointments_tab
    type: Tab
  - identifier: organizer_tab
    type: Tab
  - identifier: organizer
    type: Relation
    foreign_table: tx_ximatypo3calendar_domain_model_organizer
    allowed: tx_ximatypo3calendar_domain_model_organizer
  - identifier: hosts
    type: Relation
    foreign_table: fe_users
    allowed: fe_users
  - identifier: category_tab
    type: Tab
  - identifier: categories
    type: Category
  - identifier: registration_tab
    type: Tab
  - identifier: registration_palette
    type: Palette
    fields:
      - identifier: requires_registration
        type: Checkbox
        default: 0
      - identifier: registration_link
        type: Link
        allowedTypes:
          - url
          - page
      - identifier: registration_deadline
        type: DateTime
        dbType: datetime
      - identifier: fee
        type: Text
  - identifier: registration_address
    type: Textarea
    rows: 3
  - identifier: workflow_tab
    type: Tab
  - identifier: workflow_palette
    type: Palette
    fields:
      - identifier: owner
        type: Select
        renderType: selectSingle
        foreign_table: fe_users
        foreign_field: events
        relationType: ManyToOne
        required: true
      - identifier: status
        type: Select
        renderType: selectSingle
        items:
          - value: 0
            label: 'Entwurf'
          - value: 1
            label: 'Live'
          - value: 2
            label: 'Abgelehnt'
  - identifier: approval_date
    type: DateTime
    dbType: datetime
