services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XimaTypo3Calendar\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  # Public services for T3api
  Xima\XimaTypo3Calendar\OperationHandler\EventChangeRequestOperationHandler:
    public: true

  Xima\XimaTypo3Calendar\EventListener\T3api\BeforeOperationAccessGrantedEventListener:
    public: true

  Xima\XimaTypo3Calendar\Hooks\DataHandlerHook:
    public: true

  Xima\XimaTypo3Calendar\Widgets\Provider\ReadyToPublishEventsDataProvider:
    arguments:
      $limit: 8

  Xima\XimaTypo3Calendar\Widgets\Provider\SoonNeededRequirementsDataProvider:
    arguments:
      $daysInPreview: 2
      $limit: 10

  xima_typo3_calendar_widget.button.calendar_events_event:
    class: 'Xima\XimaTypo3Calendar\Widgets\Provider\ModuleButtonProvider'
    arguments:
      $routeIdentifier: 'calendar_events'
      $table: 'tx_ximatypo3calendar_domain_model_event'
      $title: 'LLL:EXT:xima_typo3_calendar/Resources/Private/Language/locallang.xlf:widget.button.calendar_events'

  xima_typo3_calendar_widget.button.calendar_events_entry:
    class: 'Xima\XimaTypo3Calendar\Widgets\Provider\ModuleButtonProvider'
    arguments:
      $routeIdentifier: 'calendar_events'
      $table: 'tx_ximatypo3calendar_domain_model_entry'
      $title: 'LLL:EXT:xima_typo3_calendar/Resources/Private/Language/locallang.xlf:widget.button.calendar_appointments'

  dashboard.widget.xima_readytopublishevents:
    class: 'Xima\XimaTypo3Calendar\Widgets\CalendarWidget'
    arguments:
      $buttonProvider: '@xima_typo3_calendar_widget.button.calendar_events_event'
      $dataProvider: '@Xima\XimaTypo3Calendar\Widgets\Provider\ReadyToPublishEventsDataProvider'
      $options:
        refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: 'xima_readytopublishevents'
        groupNames: 'xima_typo3_calendar'
        title: 'LLL:EXT:xima_typo3_calendar/Resources/Private/Language/locallang.xlf:widget.ready_to_publish_events.title'
        description: 'LLL:EXT:xima_typo3_calendar/Resources/Private/Language/locallang.xlf:widget.ready_to_publish_events.description'
        iconIdentifier: 'content-widget-list'
        height: 'large'
        width: 'medium'

  dashboard.widget.xima_upcomingappointments:
    class: 'Xima\XimaTypo3Calendar\Widgets\CalendarWidget'
    arguments:
      $buttonProvider: '@xima_typo3_calendar_widget.button.calendar_events_entry'
      $dataProvider: '@Xima\XimaTypo3Calendar\Widgets\Provider\UpcomingAppointmentsDataProvider'
      $options:
        refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: 'xima_upcomingappointments'
        groupNames: 'xima_typo3_calendar'
        title: 'LLL:EXT:xima_typo3_calendar/Resources/Private/Language/locallang.xlf:widget.upcoming_appointments.title'
        description: 'LLL:EXT:xima_typo3_calendar/Resources/Private/Language/locallang.xlf:widget.upcoming_appointments.description'
        iconIdentifier: 'content-widget-list'
        height: 'large'
        width: 'medium'

  dashboard.widget.xima_soonneededrequirements:
    class: 'Xima\XimaTypo3Calendar\Widgets\CalendarWidget'
    arguments:
      $buttonProvider: '@xima_typo3_calendar_widget.button.calendar_events_entry'
      $dataProvider: '@Xima\XimaTypo3Calendar\Widgets\Provider\SoonNeededRequirementsDataProvider'
      $options:
        refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: 'xima_soonneededrequirements'
        groupNames: 'xima_typo3_calendar'
        title: 'LLL:EXT:xima_typo3_calendar/Resources/Private/Language/locallang.xlf:widget.soon_needed_requirements.title'
        description: 'LLL:EXT:xima_typo3_calendar/Resources/Private/Language/locallang.xlf:widget.soon_needed_requirements.description'
        iconIdentifier: 'content-widget-list'
        height: 'medium'
        width: 'large'

  dashboard.widget.xima_canceledappointments:
    class: 'Xima\XimaTypo3Calendar\Widgets\CalendarWidget'
    arguments:
      $buttonProvider: '@xima_typo3_calendar_widget.button.calendar_events_event'
      $dataProvider: '@Xima\XimaTypo3Calendar\Widgets\Provider\CanceledAppointmentsDataProvider'
      $options:
        refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: 'xima_canceledappointments'
        groupNames: 'xima_typo3_calendar'
        title: 'LLL:EXT:xima_typo3_calendar/Resources/Private/Language/locallang.xlf:widget.canceled_appointments.title'
        description: 'LLL:EXT:xima_typo3_calendar/Resources/Private/Language/locallang.xlf:widget.canceled_appointments.description'
        iconIdentifier: 'content-widget-list'
        height: 'medium'
        width: 'large'
